### ISSUE TITLE
Cursor offset error with custom domain name

### ISSUE THREAD

**Issue by silentboatman** [hbons/Lockee#11]
If you set a custom domain in config.json, the cursor is in the wrong place when you click on the "Go to locker"-button.

![custom_domain_error](https://cloud.githubusercontent.com/assets/5294234/7955411/6db22330-09d8-11e5-9728-59c5f987dd3e.png)

I found the `putCursorAtEnd()` function in `client.js`, but the problem seems to be that the `padding-left` (that is set in `default.css` on line 306) doesn't changed when you set a custom domain. But I don't know how to change that, since `padding-left` is set in pixels.

**Comment by hbons** [comment]
Should probaly measure the width of the text if possible with javascipt and use that to calculate the padding.

**Comment by silentboatman** [comment]
Fixed it! PR comming :)
